// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one

INSERT INTO attachments (
    person_id, owner_user_id, kind, filename, storage_key, mime_type, size_bytes
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, person_id, owner_user_id, kind, filename, storage_key, mime_type, size_bytes, created_at
`

type CreateAttachmentParams struct {
	PersonID    pgtype.UUID `json:"person_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Kind        string      `json:"kind"`
	Filename    string      `json:"filename"`
	StorageKey  string      `json:"storage_key"`
	MimeType    *string     `json:"mime_type"`
	SizeBytes   *int64      `json:"size_bytes"`
}

// attachments.sql
// File attachments tied to people, scoped by owner_user_id.
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.PersonID,
		arg.OwnerUserID,
		arg.Kind,
		arg.Filename,
		arg.StorageKey,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.OwnerUserID,
		&i.Kind,
		&i.Filename,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments
WHERE id = $1 AND owner_user_id = $2
`

type DeleteAttachmentParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error {
	_, err := q.db.Exec(ctx, deleteAttachment, arg.ID, arg.OwnerUserID)
	return err
}

const listAttachmentsByPerson = `-- name: ListAttachmentsByPerson :many
SELECT id, person_id, owner_user_id, kind, filename, storage_key, mime_type, size_bytes, created_at FROM attachments
WHERE person_id = $1 AND owner_user_id = $2
ORDER BY created_at DESC
`

type ListAttachmentsByPersonParams struct {
	PersonID    pgtype.UUID `json:"person_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) ListAttachmentsByPerson(ctx context.Context, arg ListAttachmentsByPersonParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByPerson, arg.PersonID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.OwnerUserID,
			&i.Kind,
			&i.Filename,
			&i.StorageKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
