// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_log (user_id, action, entity, entity_id, ip, meta)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, action, entity, entity_id, ip, meta, created_at
`

type CreateAuditLogParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Action   string      `json:"action"`
	Entity   *string     `json:"entity"`
	EntityID pgtype.UUID `json:"entity_id"`
	Ip       *string     `json:"ip"`
	Meta     []byte      `json:"meta"`
}

// audit.sql
// Append-only audit log for security-relevant user actions.
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Ip,
		arg.Meta,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Entity,
		&i.EntityID,
		&i.Ip,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogByUser = `-- name: ListAuditLogByUser :many
SELECT id, user_id, action, entity, entity_id, ip, meta, created_at FROM audit_log
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAuditLogByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListAuditLogByUser(ctx context.Context, arg ListAuditLogByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByUser, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Ip,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
