// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (
    owner_user_id, person_id, title, type, event_date,
    is_recurring, recurrence_rule, notes
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE($6, false),
    $7,
    $8
)
RETURNING id, owner_user_id, person_id, title, type, event_date, is_recurring, recurrence_rule, notes, created_at, updated_at
`

type CreateEventParams struct {
	OwnerUserID    pgtype.UUID `json:"owner_user_id"`
	PersonID       pgtype.UUID `json:"person_id"`
	Title          string      `json:"title"`
	Type           string      `json:"type"`
	EventDate      pgtype.Date `json:"event_date"`
	IsRecurring    interface{} `json:"is_recurring"`
	RecurrenceRule *string     `json:"recurrence_rule"`
	Notes          *string     `json:"notes"`
}

// events.sql
// Dated events tied to people, scoped by owner_user_id.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.OwnerUserID,
		arg.PersonID,
		arg.Title,
		arg.Type,
		arg.EventDate,
		arg.IsRecurring,
		arg.RecurrenceRule,
		arg.Notes,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.PersonID,
		&i.Title,
		&i.Type,
		&i.EventDate,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1 AND owner_user_id = $2
`

type DeleteEventParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.Exec(ctx, deleteEvent, arg.ID, arg.OwnerUserID)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, owner_user_id, person_id, title, type, event_date, is_recurring, recurrence_rule, notes, created_at, updated_at FROM events
WHERE id = $1 AND owner_user_id = $2
`

type GetEventByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, arg.ID, arg.OwnerUserID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.PersonID,
		&i.Title,
		&i.Type,
		&i.EventDate,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsByOwner = `-- name: ListEventsByOwner :many
SELECT id, owner_user_id, person_id, title, type, event_date, is_recurring, recurrence_rule, notes, created_at, updated_at FROM events
WHERE owner_user_id = $1
ORDER BY event_date DESC
LIMIT $3 OFFSET $2
`

type ListEventsByOwnerParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Offset      int32       `json:"offset"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListEventsByOwner(ctx context.Context, arg ListEventsByOwnerParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByOwner, arg.OwnerUserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.PersonID,
			&i.Title,
			&i.Type,
			&i.EventDate,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByPerson = `-- name: ListEventsByPerson :many
SELECT id, owner_user_id, person_id, title, type, event_date, is_recurring, recurrence_rule, notes, created_at, updated_at FROM events
WHERE person_id = $1 AND owner_user_id = $2
ORDER BY event_date DESC
`

type ListEventsByPersonParams struct {
	PersonID    pgtype.UUID `json:"person_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) ListEventsByPerson(ctx context.Context, arg ListEventsByPersonParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByPerson, arg.PersonID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.PersonID,
			&i.Title,
			&i.Type,
			&i.EventDate,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT id, owner_user_id, person_id, title, type, event_date, is_recurring, recurrence_rule, notes, created_at, updated_at FROM events
WHERE owner_user_id = $1
  AND event_date >= current_date
  AND event_date <= current_date + $2::int
ORDER BY event_date
`

type ListUpcomingEventsParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	DaysAhead   int32       `json:"days_ahead"`
}

func (q *Queries) ListUpcomingEvents(ctx context.Context, arg ListUpcomingEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listUpcomingEvents, arg.OwnerUserID, arg.DaysAhead)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.PersonID,
			&i.Title,
			&i.Type,
			&i.EventDate,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    person_id       = $1,
    title           = $2,
    type            = $3,
    event_date      = $4,
    is_recurring    = COALESCE($5, false),
    recurrence_rule = $6,
    notes           = $7,
    updated_at      = now()
WHERE id = $8 AND owner_user_id = $9
RETURNING id, owner_user_id, person_id, title, type, event_date, is_recurring, recurrence_rule, notes, created_at, updated_at
`

type UpdateEventParams struct {
	PersonID       pgtype.UUID `json:"person_id"`
	Title          string      `json:"title"`
	Type           string      `json:"type"`
	EventDate      pgtype.Date `json:"event_date"`
	IsRecurring    bool        `json:"is_recurring"`
	RecurrenceRule *string     `json:"recurrence_rule"`
	Notes          *string     `json:"notes"`
	ID             pgtype.UUID `json:"id"`
	OwnerUserID    pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.PersonID,
		arg.Title,
		arg.Type,
		arg.EventDate,
		arg.IsRecurring,
		arg.RecurrenceRule,
		arg.Notes,
		arg.ID,
		arg.OwnerUserID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.PersonID,
		&i.Title,
		&i.Type,
		&i.EventDate,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
