// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID          pgtype.UUID        `json:"id"`
	PersonID    pgtype.UUID        `json:"person_id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Kind        string             `json:"kind"`
	Filename    string             `json:"filename"`
	StorageKey  string             `json:"storage_key"`
	MimeType    *string            `json:"mime_type"`
	SizeBytes   *int64             `json:"size_bytes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Action    string             `json:"action"`
	Entity    *string            `json:"entity"`
	EntityID  pgtype.UUID        `json:"entity_id"`
	Ip        *string            `json:"ip"`
	Meta      []byte             `json:"meta"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CustomField struct {
	ID        pgtype.UUID        `json:"id"`
	PersonID  pgtype.UUID        `json:"person_id"`
	Key       string             `json:"key"`
	Value     *string            `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID             pgtype.UUID        `json:"id"`
	OwnerUserID    pgtype.UUID        `json:"owner_user_id"`
	PersonID       pgtype.UUID        `json:"person_id"`
	Title          string             `json:"title"`
	Type           string             `json:"type"`
	EventDate      pgtype.Date        `json:"event_date"`
	IsRecurring    bool               `json:"is_recurring"`
	RecurrenceRule *string            `json:"recurrence_rule"`
	Notes          *string            `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Person struct {
	ID             pgtype.UUID        `json:"id"`
	OwnerUserID    pgtype.UUID        `json:"owner_user_id"`
	FullName       string             `json:"full_name"`
	Nickname       *string            `json:"nickname"`
	AvatarUrl      *string            `json:"avatar_url"`
	Relationship   *string            `json:"relationship"`
	Birthday       pgtype.Date        `json:"birthday"`
	Anniversary    pgtype.Date        `json:"anniversary"`
	NamedayCountry *string            `json:"nameday_country"`
	NamedayMonth   *int32             `json:"nameday_month"`
	NamedayDay     *int32             `json:"nameday_day"`
	AgeVisible     bool               `json:"age_visible"`
	Address        *string            `json:"address"`
	Phone          *string            `json:"phone"`
	Email          *string            `json:"email"`
	Notes          *string            `json:"notes"`
	FavoriteThings *string            `json:"favorite_things"`
	GiftIdeas      *string            `json:"gift_ideas"`
	Interests      *string            `json:"interests"`
	IsFavorite     bool               `json:"is_favorite"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PersonTag struct {
	PersonID pgtype.UUID `json:"person_id"`
	TagID    pgtype.UUID `json:"tag_id"`
}

type Relationship struct {
	ID           pgtype.UUID        `json:"id"`
	OwnerUserID  pgtype.UUID        `json:"owner_user_id"`
	FromPersonID pgtype.UUID        `json:"from_person_id"`
	ToPersonID   pgtype.UUID        `json:"to_person_id"`
	Kind         string             `json:"kind"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Reminder struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	EventID     pgtype.UUID        `json:"event_id"`
	LeadDays    int32              `json:"lead_days"`
	FiredAt     pgtype.Timestamptz `json:"fired_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	RememberMe bool               `json:"remember_me"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Ip         *string            `json:"ip"`
	UserAgent  *string            `json:"user_agent"`
}

type SocialLink struct {
	ID        pgtype.UUID        `json:"id"`
	PersonID  pgtype.UUID        `json:"person_id"`
	Platform  string             `json:"platform"`
	Url       string             `json:"url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TimelineEntry struct {
	ID          pgtype.UUID        `json:"id"`
	PersonID    pgtype.UUID        `json:"person_id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Type        string             `json:"type"`
	Title       *string            `json:"title"`
	Body        *string            `json:"body"`
	OccurredOn  pgtype.Date        `json:"occurred_on"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Name            *string            `json:"name"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserSetting struct {
	UserID                  pgtype.UUID        `json:"user_id"`
	NamedayCountry          string             `json:"nameday_country"`
	Theme                   string             `json:"theme"`
	DefaultReminderLeadDays int32              `json:"default_reminder_lead_days"`
	Onboarded               bool               `json:"onboarded"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}
