// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPeopleByOwner = `-- name: CountPeopleByOwner :one
SELECT COUNT(*) FROM people WHERE owner_user_id = $1
`

func (q *Queries) CountPeopleByOwner(ctx context.Context, ownerUserID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPeopleByOwner, ownerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPerson = `-- name: CreatePerson :one

INSERT INTO people (
    owner_user_id, full_name, nickname, avatar_url, relationship,
    birthday, anniversary, nameday_country, nameday_month, nameday_day,
    age_visible, address, phone, email, notes, favorite_things,
    gift_ideas, interests, is_favorite
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    COALESCE($11, true),
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    COALESCE($19, false)
)
RETURNING id, owner_user_id, full_name, nickname, avatar_url, relationship, birthday, anniversary, nameday_country, nameday_month, nameday_day, age_visible, address, phone, email, notes, favorite_things, gift_ideas, interests, is_favorite, created_at, updated_at
`

type CreatePersonParams struct {
	OwnerUserID    pgtype.UUID `json:"owner_user_id"`
	FullName       string      `json:"full_name"`
	Nickname       *string     `json:"nickname"`
	AvatarUrl      *string     `json:"avatar_url"`
	Relationship   *string     `json:"relationship"`
	Birthday       pgtype.Date `json:"birthday"`
	Anniversary    pgtype.Date `json:"anniversary"`
	NamedayCountry *string     `json:"nameday_country"`
	NamedayMonth   *int32      `json:"nameday_month"`
	NamedayDay     *int32      `json:"nameday_day"`
	AgeVisible     interface{} `json:"age_visible"`
	Address        *string     `json:"address"`
	Phone          *string     `json:"phone"`
	Email          *string     `json:"email"`
	Notes          *string     `json:"notes"`
	FavoriteThings *string     `json:"favorite_things"`
	GiftIdeas      *string     `json:"gift_ideas"`
	Interests      *string     `json:"interests"`
	IsFavorite     interface{} `json:"is_favorite"`
}

// people.sql
// Core people records, scoped by owner_user_id for privacy isolation.
// Includes fuzzy search (pg_trgm), upcoming birthdays, and favorites.
func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.OwnerUserID,
		arg.FullName,
		arg.Nickname,
		arg.AvatarUrl,
		arg.Relationship,
		arg.Birthday,
		arg.Anniversary,
		arg.NamedayCountry,
		arg.NamedayMonth,
		arg.NamedayDay,
		arg.AgeVisible,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.Notes,
		arg.FavoriteThings,
		arg.GiftIdeas,
		arg.Interests,
		arg.IsFavorite,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.FullName,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Relationship,
		&i.Birthday,
		&i.Anniversary,
		&i.NamedayCountry,
		&i.NamedayMonth,
		&i.NamedayDay,
		&i.AgeVisible,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.FavoriteThings,
		&i.GiftIdeas,
		&i.Interests,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM people
WHERE id = $1 AND owner_user_id = $2
`

type DeletePersonParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) DeletePerson(ctx context.Context, arg DeletePersonParams) error {
	_, err := q.db.Exec(ctx, deletePerson, arg.ID, arg.OwnerUserID)
	return err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, owner_user_id, full_name, nickname, avatar_url, relationship, birthday, anniversary, nameday_country, nameday_month, nameday_day, age_visible, address, phone, email, notes, favorite_things, gift_ideas, interests, is_favorite, created_at, updated_at FROM people
WHERE id = $1 AND owner_user_id = $2
`

type GetPersonByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) GetPersonByID(ctx context.Context, arg GetPersonByIDParams) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByID, arg.ID, arg.OwnerUserID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.FullName,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Relationship,
		&i.Birthday,
		&i.Anniversary,
		&i.NamedayCountry,
		&i.NamedayMonth,
		&i.NamedayDay,
		&i.AgeVisible,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.FavoriteThings,
		&i.GiftIdeas,
		&i.Interests,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPeopleByOwner = `-- name: ListPeopleByOwner :many
SELECT id, owner_user_id, full_name, nickname, avatar_url, relationship, birthday, anniversary, nameday_country, nameday_month, nameday_day, age_visible, address, phone, email, notes, favorite_things, gift_ideas, interests, is_favorite, created_at, updated_at FROM people
WHERE owner_user_id = $1
ORDER BY full_name
LIMIT $3 OFFSET $2
`

type ListPeopleByOwnerParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Offset      int32       `json:"offset"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListPeopleByOwner(ctx context.Context, arg ListPeopleByOwnerParams) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPeopleByOwner, arg.OwnerUserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.FullName,
			&i.Nickname,
			&i.AvatarUrl,
			&i.Relationship,
			&i.Birthday,
			&i.Anniversary,
			&i.NamedayCountry,
			&i.NamedayMonth,
			&i.NamedayDay,
			&i.AgeVisible,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Notes,
			&i.FavoriteThings,
			&i.GiftIdeas,
			&i.Interests,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentlyAddedByOwner = `-- name: ListRecentlyAddedByOwner :many
SELECT id, owner_user_id, full_name, nickname, avatar_url, relationship, birthday, anniversary, nameday_country, nameday_month, nameday_day, age_visible, address, phone, email, notes, favorite_things, gift_ideas, interests, is_favorite, created_at, updated_at FROM people
WHERE owner_user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentlyAddedByOwnerParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListRecentlyAddedByOwner(ctx context.Context, arg ListRecentlyAddedByOwnerParams) ([]Person, error) {
	rows, err := q.db.Query(ctx, listRecentlyAddedByOwner, arg.OwnerUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.FullName,
			&i.Nickname,
			&i.AvatarUrl,
			&i.Relationship,
			&i.Birthday,
			&i.Anniversary,
			&i.NamedayCountry,
			&i.NamedayMonth,
			&i.NamedayDay,
			&i.AgeVisible,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Notes,
			&i.FavoriteThings,
			&i.GiftIdeas,
			&i.Interests,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingBirthdays = `-- name: ListUpcomingBirthdays :many
SELECT id, owner_user_id, full_name, nickname, avatar_url, relationship, birthday, anniversary, nameday_country, nameday_month, nameday_day, age_visible, address, phone, email, notes, favorite_things, gift_ideas, interests, is_favorite, created_at, updated_at,
    CASE
        WHEN make_date(extract(year FROM now())::int,
                       extract(month FROM birthday)::int,
                       extract(day FROM birthday)::int) >= current_date
        THEN make_date(extract(year FROM now())::int,
                       extract(month FROM birthday)::int,
                       extract(day FROM birthday)::int)
        ELSE make_date(extract(year FROM now())::int + 1,
                       extract(month FROM birthday)::int,
                       extract(day FROM birthday)::int)
    END AS next_birthday
FROM people
WHERE owner_user_id = $1
  AND birthday IS NOT NULL
  AND (
    CASE
        WHEN make_date(extract(year FROM now())::int,
                       extract(month FROM birthday)::int,
                       extract(day FROM birthday)::int) >= current_date
        THEN make_date(extract(year FROM now())::int,
                       extract(month FROM birthday)::int,
                       extract(day FROM birthday)::int)
        ELSE make_date(extract(year FROM now())::int + 1,
                       extract(month FROM birthday)::int,
                       extract(day FROM birthday)::int)
    END
  ) <= current_date + $2::int
ORDER BY next_birthday
`

type ListUpcomingBirthdaysParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	DaysAhead   int32       `json:"days_ahead"`
}

type ListUpcomingBirthdaysRow struct {
	ID             pgtype.UUID        `json:"id"`
	OwnerUserID    pgtype.UUID        `json:"owner_user_id"`
	FullName       string             `json:"full_name"`
	Nickname       *string            `json:"nickname"`
	AvatarUrl      *string            `json:"avatar_url"`
	Relationship   *string            `json:"relationship"`
	Birthday       pgtype.Date        `json:"birthday"`
	Anniversary    pgtype.Date        `json:"anniversary"`
	NamedayCountry *string            `json:"nameday_country"`
	NamedayMonth   *int32             `json:"nameday_month"`
	NamedayDay     *int32             `json:"nameday_day"`
	AgeVisible     bool               `json:"age_visible"`
	Address        *string            `json:"address"`
	Phone          *string            `json:"phone"`
	Email          *string            `json:"email"`
	Notes          *string            `json:"notes"`
	FavoriteThings *string            `json:"favorite_things"`
	GiftIdeas      *string            `json:"gift_ideas"`
	Interests      *string            `json:"interests"`
	IsFavorite     bool               `json:"is_favorite"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	NextBirthday   interface{}        `json:"next_birthday"`
}

// Computes the next birthday occurrence (this year or next year if past)
// and returns people whose next birthday falls within `days_ahead` days.
func (q *Queries) ListUpcomingBirthdays(ctx context.Context, arg ListUpcomingBirthdaysParams) ([]ListUpcomingBirthdaysRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingBirthdays, arg.OwnerUserID, arg.DaysAhead)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingBirthdaysRow
	for rows.Next() {
		var i ListUpcomingBirthdaysRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.FullName,
			&i.Nickname,
			&i.AvatarUrl,
			&i.Relationship,
			&i.Birthday,
			&i.Anniversary,
			&i.NamedayCountry,
			&i.NamedayMonth,
			&i.NamedayDay,
			&i.AgeVisible,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Notes,
			&i.FavoriteThings,
			&i.GiftIdeas,
			&i.Interests,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextBirthday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPeople = `-- name: SearchPeople :many
SELECT id, owner_user_id, full_name, nickname, avatar_url, relationship, birthday, anniversary, nameday_country, nameday_month, nameday_day, age_visible, address, phone, email, notes, favorite_things, gift_ideas, interests, is_favorite, created_at, updated_at FROM people
WHERE owner_user_id = $1
  AND (
    full_name ILIKE '%' || $2 || '%'
    OR nickname ILIKE '%' || $2 || '%'
    OR notes ILIKE '%' || $2 || '%'
    OR interests ILIKE '%' || $2 || '%'
    OR full_name % $2
    OR nickname % $2
  )
ORDER BY full_name
LIMIT $4 OFFSET $3
`

type SearchPeopleParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Query       *string     `json:"query"`
	Offset      int32       `json:"offset"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) SearchPeople(ctx context.Context, arg SearchPeopleParams) ([]Person, error) {
	rows, err := q.db.Query(ctx, searchPeople,
		arg.OwnerUserID,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.FullName,
			&i.Nickname,
			&i.AvatarUrl,
			&i.Relationship,
			&i.Birthday,
			&i.Anniversary,
			&i.NamedayCountry,
			&i.NamedayMonth,
			&i.NamedayDay,
			&i.AgeVisible,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Notes,
			&i.FavoriteThings,
			&i.GiftIdeas,
			&i.Interests,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFavorite = `-- name: SetFavorite :exec
UPDATE people
SET is_favorite = $1, updated_at = now()
WHERE id = $2 AND owner_user_id = $3
`

type SetFavoriteParams struct {
	IsFavorite  bool        `json:"is_favorite"`
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) error {
	_, err := q.db.Exec(ctx, setFavorite, arg.IsFavorite, arg.ID, arg.OwnerUserID)
	return err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE people SET
    full_name       = $1,
    nickname        = $2,
    avatar_url      = $3,
    relationship    = $4,
    birthday        = $5,
    anniversary     = $6,
    nameday_country = $7,
    nameday_month   = $8,
    nameday_day     = $9,
    age_visible     = COALESCE($10, true),
    address         = $11,
    phone           = $12,
    email           = $13,
    notes           = $14,
    favorite_things = $15,
    gift_ideas      = $16,
    interests       = $17,
    is_favorite     = COALESCE($18, false),
    updated_at      = now()
WHERE id = $19 AND owner_user_id = $20
RETURNING id, owner_user_id, full_name, nickname, avatar_url, relationship, birthday, anniversary, nameday_country, nameday_month, nameday_day, age_visible, address, phone, email, notes, favorite_things, gift_ideas, interests, is_favorite, created_at, updated_at
`

type UpdatePersonParams struct {
	FullName       string      `json:"full_name"`
	Nickname       *string     `json:"nickname"`
	AvatarUrl      *string     `json:"avatar_url"`
	Relationship   *string     `json:"relationship"`
	Birthday       pgtype.Date `json:"birthday"`
	Anniversary    pgtype.Date `json:"anniversary"`
	NamedayCountry *string     `json:"nameday_country"`
	NamedayMonth   *int32      `json:"nameday_month"`
	NamedayDay     *int32      `json:"nameday_day"`
	AgeVisible     bool        `json:"age_visible"`
	Address        *string     `json:"address"`
	Phone          *string     `json:"phone"`
	Email          *string     `json:"email"`
	Notes          *string     `json:"notes"`
	FavoriteThings *string     `json:"favorite_things"`
	GiftIdeas      *string     `json:"gift_ideas"`
	Interests      *string     `json:"interests"`
	IsFavorite     bool        `json:"is_favorite"`
	ID             pgtype.UUID `json:"id"`
	OwnerUserID    pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.FullName,
		arg.Nickname,
		arg.AvatarUrl,
		arg.Relationship,
		arg.Birthday,
		arg.Anniversary,
		arg.NamedayCountry,
		arg.NamedayMonth,
		arg.NamedayDay,
		arg.AgeVisible,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.Notes,
		arg.FavoriteThings,
		arg.GiftIdeas,
		arg.Interests,
		arg.IsFavorite,
		arg.ID,
		arg.OwnerUserID,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.FullName,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Relationship,
		&i.Birthday,
		&i.Anniversary,
		&i.NamedayCountry,
		&i.NamedayMonth,
		&i.NamedayDay,
		&i.AgeVisible,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.FavoriteThings,
		&i.GiftIdeas,
		&i.Interests,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
