// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AttachTagToPerson(ctx context.Context, arg AttachTagToPersonParams) error
	// attachments.sql
	// File attachments tied to people, scoped by owner_user_id.
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	// audit.sql
	// Append-only audit log for security-relevant user actions.
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// events.sql
	// Dated events tied to people, scoped by owner_user_id.
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	// people.sql
	// Core people records, scoped by owner_user_id for privacy isolation.
	// Includes fuzzy search (pg_trgm), upcoming birthdays, and favorites.
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	// relationships.sql
	// Directed relationships between people, scoped by owner_user_id.
	CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (Relationship, error)
	// reminders.sql
	// Reminders for events, scoped by owner_user_id. Pending = not yet fired and due.
	CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error)
	// sessions.sql
	// Authenticated session lifecycle. Token is stored hashed for safety.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// tags.sql
	// Owner-scoped tags and person/tag associations.
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	// timeline.sql
	// Per-person timeline entries, scoped by owner_user_id.
	CreateTimelineEntry(ctx context.Context, arg CreateTimelineEntryParams) (TimelineEntry, error)
	// users.sql
	// User accounts and per-user settings. Settings are upserted by user_id.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error
	DeleteEvent(ctx context.Context, arg DeleteEventParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeletePerson(ctx context.Context, arg DeletePersonParams) error
	DeleteRelationship(ctx context.Context, arg DeleteRelationshipParams) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) error
	DeleteTimelineEntry(ctx context.Context, arg DeleteTimelineEntryParams) error
	DetachTagFromPerson(ctx context.Context, arg DetachTagFromPersonParams) error
	GetEventByID(ctx context.Context, arg GetEventByIDParams) (Event, error)
	GetPersonByID(ctx context.Context, arg GetPersonByIDParams) (Person, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserSettings(ctx context.Context, userID pgtype.UUID) (UserSetting, error)
	ListAttachmentsByPerson(ctx context.Context, arg ListAttachmentsByPersonParams) ([]Attachment, error)
	ListAuditLogByUser(ctx context.Context, arg ListAuditLogByUserParams) ([]AuditLog, error)
	ListEventsByOwner(ctx context.Context, arg ListEventsByOwnerParams) ([]Event, error)
	ListEventsByPerson(ctx context.Context, arg ListEventsByPersonParams) ([]Event, error)
	// A reminder is due when (event_date - lead_days) <= now() and not yet fired.
	ListPendingReminders(ctx context.Context, ownerUserID pgtype.UUID) ([]Reminder, error)
	ListPeopleByOwner(ctx context.Context, arg ListPeopleByOwnerParams) ([]Person, error)
	ListRecentlyAddedByOwner(ctx context.Context, arg ListRecentlyAddedByOwnerParams) ([]Person, error)
	ListRelationshipsForPerson(ctx context.Context, arg ListRelationshipsForPersonParams) ([]Relationship, error)
	ListRemindersByEvent(ctx context.Context, arg ListRemindersByEventParams) ([]Reminder, error)
	ListRemindersByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]Reminder, error)
	ListTagsByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]Tag, error)
	ListTagsForPerson(ctx context.Context, arg ListTagsForPersonParams) ([]Tag, error)
	ListTimelineByPerson(ctx context.Context, arg ListTimelineByPersonParams) ([]TimelineEntry, error)
	// Computes the next birthday occurrence (this year or next year if past)
	// and returns people whose next birthday falls within `days_ahead` days.
	ListUpcomingBirthdays(ctx context.Context, arg ListUpcomingBirthdaysParams) ([]ListUpcomingBirthdaysRow, error)
	ListUpcomingEvents(ctx context.Context, arg ListUpcomingEventsParams) ([]Event, error)
	MarkReminderFired(ctx context.Context, arg MarkReminderFiredParams) error
	SearchPeople(ctx context.Context, arg SearchPeopleParams) ([]Person, error)
	SetFavorite(ctx context.Context, arg SetFavoriteParams) error
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error)
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error)
	VerifyEmail(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
