// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relationships.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRelationship = `-- name: CreateRelationship :one

INSERT INTO relationships (owner_user_id, from_person_id, to_person_id, kind)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, owner_user_id, from_person_id, to_person_id, kind, created_at
`

type CreateRelationshipParams struct {
	OwnerUserID  pgtype.UUID `json:"owner_user_id"`
	FromPersonID pgtype.UUID `json:"from_person_id"`
	ToPersonID   pgtype.UUID `json:"to_person_id"`
	Kind         string      `json:"kind"`
}

// relationships.sql
// Directed relationships between people, scoped by owner_user_id.
func (q *Queries) CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, createRelationship,
		arg.OwnerUserID,
		arg.FromPersonID,
		arg.ToPersonID,
		arg.Kind,
	)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.FromPersonID,
		&i.ToPersonID,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRelationship = `-- name: DeleteRelationship :exec
DELETE FROM relationships
WHERE id = $1 AND owner_user_id = $2
`

type DeleteRelationshipParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteRelationship(ctx context.Context, arg DeleteRelationshipParams) error {
	_, err := q.db.Exec(ctx, deleteRelationship, arg.ID, arg.OwnerUserID)
	return err
}

const listRelationshipsForPerson = `-- name: ListRelationshipsForPerson :many
SELECT id, owner_user_id, from_person_id, to_person_id, kind, created_at FROM relationships
WHERE owner_user_id = $1
  AND (from_person_id = $2 OR to_person_id = $2)
ORDER BY created_at DESC
`

type ListRelationshipsForPersonParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	PersonID    pgtype.UUID `json:"person_id"`
}

func (q *Queries) ListRelationshipsForPerson(ctx context.Context, arg ListRelationshipsForPersonParams) ([]Relationship, error) {
	rows, err := q.db.Query(ctx, listRelationshipsForPerson, arg.OwnerUserID, arg.PersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Relationship
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.FromPersonID,
			&i.ToPersonID,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
