// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReminder = `-- name: CreateReminder :one

INSERT INTO reminders (owner_user_id, event_id, lead_days)
VALUES ($1, $2, $3)
RETURNING id, owner_user_id, event_id, lead_days, fired_at, created_at
`

type CreateReminderParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	EventID     pgtype.UUID `json:"event_id"`
	LeadDays    int32       `json:"lead_days"`
}

// reminders.sql
// Reminders for events, scoped by owner_user_id. Pending = not yet fired and due.
func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder, arg.OwnerUserID, arg.EventID, arg.LeadDays)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.EventID,
		&i.LeadDays,
		&i.FiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingReminders = `-- name: ListPendingReminders :many
SELECT r.id, r.owner_user_id, r.event_id, r.lead_days, r.fired_at, r.created_at
FROM reminders r
JOIN events e ON e.id = r.event_id
WHERE r.owner_user_id = $1
  AND r.fired_at IS NULL
  AND (e.event_date - (r.lead_days || ' days')::interval) <= now()
ORDER BY e.event_date
`

// A reminder is due when (event_date - lead_days) <= now() and not yet fired.
func (q *Queries) ListPendingReminders(ctx context.Context, ownerUserID pgtype.UUID) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listPendingReminders, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.EventID,
			&i.LeadDays,
			&i.FiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemindersByEvent = `-- name: ListRemindersByEvent :many
SELECT id, owner_user_id, event_id, lead_days, fired_at, created_at FROM reminders
WHERE event_id = $1 AND owner_user_id = $2
ORDER BY lead_days
`

type ListRemindersByEventParams struct {
	EventID     pgtype.UUID `json:"event_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) ListRemindersByEvent(ctx context.Context, arg ListRemindersByEventParams) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listRemindersByEvent, arg.EventID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.EventID,
			&i.LeadDays,
			&i.FiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemindersByOwner = `-- name: ListRemindersByOwner :many
SELECT id, owner_user_id, event_id, lead_days, fired_at, created_at FROM reminders
WHERE owner_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRemindersByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listRemindersByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.EventID,
			&i.LeadDays,
			&i.FiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderFired = `-- name: MarkReminderFired :exec
UPDATE reminders
SET fired_at = now()
WHERE id = $1 AND owner_user_id = $2
`

type MarkReminderFiredParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) MarkReminderFired(ctx context.Context, arg MarkReminderFiredParams) error {
	_, err := q.db.Exec(ctx, markReminderFired, arg.ID, arg.OwnerUserID)
	return err
}
