// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id, token_hash, remember_me, expires_at, ip, user_agent)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, token_hash, remember_me, expires_at, created_at, ip, user_agent
`

type CreateSessionParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	RememberMe bool               `json:"remember_me"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Ip         *string            `json:"ip"`
	UserAgent  *string            `json:"user_agent"`
}

// sessions.sql
// Authenticated session lifecycle. Token is stored hashed for safety.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.RememberMe,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.RememberMe,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, remember_me, expires_at, created_at, ip, user_agent FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.RememberMe,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}
