// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachTagToPerson = `-- name: AttachTagToPerson :exec
INSERT INTO person_tags (person_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachTagToPersonParams struct {
	PersonID pgtype.UUID `json:"person_id"`
	TagID    pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AttachTagToPerson(ctx context.Context, arg AttachTagToPersonParams) error {
	_, err := q.db.Exec(ctx, attachTagToPerson, arg.PersonID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one

INSERT INTO tags (owner_user_id, name)
VALUES ($1, $2)
RETURNING id, owner_user_id, name, created_at
`

type CreateTagParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Name        string      `json:"name"`
}

// tags.sql
// Owner-scoped tags and person/tag associations.
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.OwnerUserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1 AND owner_user_id = $2
`

type DeleteTagParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.OwnerUserID)
	return err
}

const detachTagFromPerson = `-- name: DetachTagFromPerson :exec
DELETE FROM person_tags
WHERE person_id = $1 AND tag_id = $2
`

type DetachTagFromPersonParams struct {
	PersonID pgtype.UUID `json:"person_id"`
	TagID    pgtype.UUID `json:"tag_id"`
}

func (q *Queries) DetachTagFromPerson(ctx context.Context, arg DetachTagFromPersonParams) error {
	_, err := q.db.Exec(ctx, detachTagFromPerson, arg.PersonID, arg.TagID)
	return err
}

const listTagsByOwner = `-- name: ListTagsByOwner :many
SELECT id, owner_user_id, name, created_at FROM tags
WHERE owner_user_id = $1
ORDER BY name
`

func (q *Queries) ListTagsByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForPerson = `-- name: ListTagsForPerson :many
SELECT t.id, t.owner_user_id, t.name, t.created_at FROM tags t
JOIN person_tags pt ON pt.tag_id = t.id
WHERE pt.person_id = $1
  AND t.owner_user_id = $2
ORDER BY t.name
`

type ListTagsForPersonParams struct {
	PersonID    pgtype.UUID `json:"person_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) ListTagsForPerson(ctx context.Context, arg ListTagsForPersonParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsForPerson, arg.PersonID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
