// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timeline.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimelineEntry = `-- name: CreateTimelineEntry :one

INSERT INTO timeline_entries (
    person_id, owner_user_id, type, title, body, occurred_on
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, person_id, owner_user_id, type, title, body, occurred_on, created_at, updated_at
`

type CreateTimelineEntryParams struct {
	PersonID    pgtype.UUID `json:"person_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	Type        string      `json:"type"`
	Title       *string     `json:"title"`
	Body        *string     `json:"body"`
	OccurredOn  pgtype.Date `json:"occurred_on"`
}

// timeline.sql
// Per-person timeline entries, scoped by owner_user_id.
func (q *Queries) CreateTimelineEntry(ctx context.Context, arg CreateTimelineEntryParams) (TimelineEntry, error) {
	row := q.db.QueryRow(ctx, createTimelineEntry,
		arg.PersonID,
		arg.OwnerUserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.OccurredOn,
	)
	var i TimelineEntry
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.OwnerUserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.OccurredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTimelineEntry = `-- name: DeleteTimelineEntry :exec
DELETE FROM timeline_entries
WHERE id = $1 AND owner_user_id = $2
`

type DeleteTimelineEntryParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteTimelineEntry(ctx context.Context, arg DeleteTimelineEntryParams) error {
	_, err := q.db.Exec(ctx, deleteTimelineEntry, arg.ID, arg.OwnerUserID)
	return err
}

const listTimelineByPerson = `-- name: ListTimelineByPerson :many
SELECT id, person_id, owner_user_id, type, title, body, occurred_on, created_at, updated_at FROM timeline_entries
WHERE person_id = $1 AND owner_user_id = $2
ORDER BY occurred_on DESC NULLS LAST, created_at DESC
`

type ListTimelineByPersonParams struct {
	PersonID    pgtype.UUID `json:"person_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) ListTimelineByPerson(ctx context.Context, arg ListTimelineByPersonParams) ([]TimelineEntry, error) {
	rows, err := q.db.Query(ctx, listTimelineByPerson, arg.PersonID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimelineEntry
	for rows.Next() {
		var i TimelineEntry
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.OwnerUserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.OccurredOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
