// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, email_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
	Name         *string `json:"name"`
}

// users.sql
// User accounts and per-user settings. Settings are upserted by user_id.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, email_verified_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, email_verified_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, nameday_country, theme, default_reminder_lead_days, onboarded, updated_at FROM user_settings WHERE user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userID pgtype.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.NamedayCountry,
		&i.Theme,
		&i.DefaultReminderLeadDays,
		&i.Onboarded,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET password_hash = $1, updated_at = now()
WHERE id = $2
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
INSERT INTO user_settings (
    user_id, nameday_country, theme, default_reminder_lead_days, onboarded
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (user_id) DO UPDATE SET
    nameday_country           = EXCLUDED.nameday_country,
    theme                     = EXCLUDED.theme,
    default_reminder_lead_days = EXCLUDED.default_reminder_lead_days,
    onboarded                 = EXCLUDED.onboarded,
    updated_at                = now()
RETURNING user_id, nameday_country, theme, default_reminder_lead_days, onboarded, updated_at
`

type UpdateUserSettingsParams struct {
	UserID                  pgtype.UUID `json:"user_id"`
	NamedayCountry          string      `json:"nameday_country"`
	Theme                   string      `json:"theme"`
	DefaultReminderLeadDays int32       `json:"default_reminder_lead_days"`
	Onboarded               bool        `json:"onboarded"`
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.UserID,
		arg.NamedayCountry,
		arg.Theme,
		arg.DefaultReminderLeadDays,
		arg.Onboarded,
	)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.NamedayCountry,
		&i.Theme,
		&i.DefaultReminderLeadDays,
		&i.Onboarded,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyEmail = `-- name: VerifyEmail :exec
UPDATE users
SET email_verified_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) VerifyEmail(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyEmail, id)
	return err
}
